import type { Metadata } from 'next';

import './globals.css';
import '@/app/GlobalStyles/style.scss';

import PagesLayout from '@/components/layouts/pagesLayout';
import Layout from '@/components/layouts/layout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<PagesLayout>
			<Layout>{children}</Layout>
		</PagesLayout>
	);
}